export {
  areExpressionsStructurallyEqual,
  collectPatternNames,
  containsFetchCall,
  countSetStateCalls,
  createComponentBindingStackTracker,
  createComponentPropStackTracker,
  createLoopAwareVisitors,
  findJsxAttribute,
  findSideEffect,
  getCallbackStatements,
  getCalleeName,
  getEffectCallback,
  getRootIdentifierName,
  hasDirective,
  hasJsxAttribute,
  hasUseServerDirective,
  isComponentAssignment,
  isComponentDeclaration,
  isHookCall,
  isMemberProperty,
  isSetterCall,
  isSetterIdentifier,
  isSimpleExpression,
  isUppercaseName,
  walkAst,
  walkInsideStatementBlocks,
} from "./utils/index.js";
