import {
  noDefaultProps,
  noGenericHandlerNames,
  noGiantComponent,
  noLegacyClassLifecycles,
  noLegacyContextApi,
  noManyBooleanProps,
  noNestedComponentDefinition,
  noReact19DeprecatedApis,
  noReactDomDeprecatedApis,
  noRenderInRender,
  noRenderPropChildren,
  reactCompilerDestructureMethod,
} from "./rules/architecture.js";
import {
  noBarrelImport,
  noDynamicImportPath,
  noFullLodashImport,
  noMoment,
  noUndeferredThirdParty,
  preferDynamicImport,
  useLazyMotion,
} from "./rules/bundle-size.js";
import { clientLocalstorageNoVersion, clientPassiveEventListeners } from "./rules/client.js";
import {
  noDarkModeGlow,
  noDisabledZoom,
  noGradientText,
  noGrayOnColoredBackground,
  noInlineBounceEasing,
  noInlineExhaustiveStyle,
  noJustifiedText,
  noLayoutTransitionInline,
  noLongTransitionDuration,
  noOutlineNone,
  noPureBlackBackground,
  noSideTabBorder,
  noTinyText,
  noWideLetterSpacing,
  noZIndex9999,
} from "./rules/design.js";
import {
  noArrayIndexAsKey,
  noPolymorphicChildren,
  noPreventDefault,
  noUncontrolledInput,
  renderingConditionalRender,
  renderingSvgPrecision,
} from "./rules/correctness.js";
import {
  asyncAwaitInLoop,
  asyncParallel,
  jsBatchDomCss,
  jsCachePropertyAccess,
  jsCacheStorage,
  jsCombineIterations,
  jsEarlyExit,
  jsFlatmapFilter,
  jsHoistIntl,
  jsHoistRegexp,
  jsIndexMaps,
  jsLengthCheckFirst,
  jsMinMaxLoop,
  jsSetMapLookups,
  jsTosortedImmutable,
} from "./rules/js-performance.js";
import {
  nextjsAsyncClientComponent,
  nextjsImageMissingSizes,
  nextjsInlineScriptMissingId,
  nextjsMissingMetadata,
  nextjsNoAElement,
  nextjsNoClientFetchForServerData,
  nextjsNoClientSideRedirect,
  nextjsNoCssLink,
  nextjsNoFontLink,
  nextjsNoHeadImport,
  nextjsNoImgElement,
  nextjsNoNativeScript,
  nextjsNoPolyfillScript,
  nextjsNoRedirectInTryCatch,
  nextjsNoSideEffectInGetHandler,
  nextjsNoUseSearchParamsWithoutSuspense,
} from "./rules/nextjs.js";
import {
  asyncDeferAwait,
  noGlobalCssVariableAnimation,
  noInlinePropOnMemoComponent,
  noLargeAnimatedBlur,
  noLayoutPropertyAnimation,
  noPermanentWillChange,
  noScaleFromZero,
  noTransitionAll,
  noUsememoSimpleExpression,
  renderingAnimateSvgWrapper,
  renderingHoistJsx,
  renderingHydrationMismatchTime,
  renderingHydrationNoFlicker,
  renderingScriptDeferAsync,
  renderingUsetransitionLoading,
  rerenderDerivedStateFromHook,
  rerenderMemoBeforeEarlyReturn,
  rerenderMemoWithDefaultValue,
  rerenderTransitionsScroll,
} from "./rules/performance.js";
import {
  noBoldHeading,
  noDefaultTailwindPalette,
  noRedundantPaddingAxes,
  noRedundantSizeAxes,
  noSpaceOnFlexChildren,
  noThreePeriodEllipsis,
  noVagueButtonLabel,
} from "./rules/react-ui.js";
import {
  rnAnimateLayoutProperty,
  rnAnimationReactionAsDerived,
  rnBottomSheetPreferNative,
  rnListCallbackPerRow,
  rnListDataMapped,
  rnListRecyclableWithoutTypes,
  rnNoDeprecatedModules,
  rnNoDimensionsGet,
  rnNoInlineFlatlistRenderitem,
  rnNoInlineObjectInListItem,
  rnNoLegacyExpoPackages,
  rnNoLegacyShadowStyles,
  rnNoNonNativeNavigator,
  rnNoRawText,
  rnNoScrollState,
  rnNoScrollviewMappedList,
  rnNoSingleElementStyleArray,
  rnPreferContentInsetAdjustment,
  rnPreferExpoImage,
  rnPreferPressable,
  rnPreferReanimated,
  rnPressableSharedValueMutation,
  rnScrollviewDynamicPadding,
  rnStylePreferBoxShadow,
} from "./rules/react-native.js";
import {
  queryMutationMissingInvalidation,
  queryNoQueryInEffect,
  queryNoRestDestructuring,
  queryNoUseQueryForMutation,
  queryNoVoidQueryFn,
  queryStableQueryClient,
} from "./rules/tanstack-query.js";
import { noEval, noSecretsInClientCode } from "./rules/security.js";
import {
  serverAfterNonblocking,
  serverAuthActions,
  serverCacheWithObjectLiteral,
  serverDedupProps,
  serverFetchWithoutRevalidate,
  serverHoistStaticIo,
  serverNoMutableModuleState,
  serverSequentialIndependentAwait,
} from "./rules/server.js";
import {
  tanstackStartGetMutation,
  tanstackStartLoaderParallelFetch,
  tanstackStartMissingHeadContent,
  tanstackStartNoAnchorElement,
  tanstackStartNoDirectFetchInLoader,
  tanstackStartNoDynamicServerFnImport,
  tanstackStartNoNavigateInRender,
  tanstackStartNoSecretsInLoader,
  tanstackStartNoUseEffectFetch,
  tanstackStartNoUseServerInHandler,
  tanstackStartRedirectInTryCatch,
  tanstackStartRoutePropertyOrder,
  tanstackStartServerFnMethodOrder,
  tanstackStartServerFnValidateInput,
} from "./rules/tanstack-start.js";
import {
  advancedEventHandlerRefs,
  effectNeedsCleanup,
  noCascadingSetState,
  noDerivedStateEffect,
  noDerivedUseState,
  noDirectStateMutation,
  noEffectChain,
  noEffectEventHandler,
  noEffectEventInDeps,
  noEventTriggerState,
  noFetchInEffect,
  noMirrorPropEffect,
  noMutableInDeps,
  noPropCallbackInEffect,
  noSetStateInRender,
  preferUseEffectEvent,
  preferUseReducer,
  preferUseSyncExternalStore,
  rerenderDependencies,
  rerenderDeferReadsHook,
  rerenderFunctionalSetstate,
  rerenderLazyStateInit,
  rerenderStateOnlyInHandlers,
} from "./rules/state-and-effects.js";
import { noDocumentStartViewTransition, noFlushSync } from "./rules/view-transitions.js";
import type { RulePlugin } from "./utils/rule-plugin.js";

const plugin: RulePlugin = {
  meta: { name: "react-doctor" },
  rules: {
    "no-derived-state-effect": noDerivedStateEffect,
    "no-fetch-in-effect": noFetchInEffect,
    "no-mirror-prop-effect": noMirrorPropEffect,
    "no-mutable-in-deps": noMutableInDeps,
    "no-cascading-set-state": noCascadingSetState,
    "no-effect-chain": noEffectChain,
    "no-effect-event-handler": noEffectEventHandler,
    "no-effect-event-in-deps": noEffectEventInDeps,
    "no-event-trigger-state": noEventTriggerState,
    "no-prop-callback-in-effect": noPropCallbackInEffect,
    "no-derived-useState": noDerivedUseState,
    "no-direct-state-mutation": noDirectStateMutation,
    "no-set-state-in-render": noSetStateInRender,
    "prefer-use-effect-event": preferUseEffectEvent,
    "prefer-useReducer": preferUseReducer,
    "prefer-use-sync-external-store": preferUseSyncExternalStore,
    "rerender-lazy-state-init": rerenderLazyStateInit,
    "rerender-functional-setstate": rerenderFunctionalSetstate,
    "rerender-dependencies": rerenderDependencies,
    "rerender-state-only-in-handlers": rerenderStateOnlyInHandlers,
    "rerender-defer-reads-hook": rerenderDeferReadsHook,
    "advanced-event-handler-refs": advancedEventHandlerRefs,
    "effect-needs-cleanup": effectNeedsCleanup,

    "no-generic-handler-names": noGenericHandlerNames,
    "no-giant-component": noGiantComponent,
    "no-many-boolean-props": noManyBooleanProps,
    "no-react19-deprecated-apis": noReact19DeprecatedApis,
    "no-render-prop-children": noRenderPropChildren,
    "no-render-in-render": noRenderInRender,
    "no-nested-component-definition": noNestedComponentDefinition,
    "react-compiler-destructure-method": reactCompilerDestructureMethod,
    "no-legacy-class-lifecycles": noLegacyClassLifecycles,
    "no-legacy-context-api": noLegacyContextApi,
    "no-default-props": noDefaultProps,
    "no-react-dom-deprecated-apis": noReactDomDeprecatedApis,

    "no-usememo-simple-expression": noUsememoSimpleExpression,
    "no-layout-property-animation": noLayoutPropertyAnimation,
    "rerender-memo-with-default-value": rerenderMemoWithDefaultValue,
    "rerender-memo-before-early-return": rerenderMemoBeforeEarlyReturn,
    "rerender-transitions-scroll": rerenderTransitionsScroll,
    "rerender-derived-state-from-hook": rerenderDerivedStateFromHook,
    "async-defer-await": asyncDeferAwait,
    "async-await-in-loop": asyncAwaitInLoop,
    "rendering-animate-svg-wrapper": renderingAnimateSvgWrapper,
    "rendering-hoist-jsx": renderingHoistJsx,
    "rendering-hydration-mismatch-time": renderingHydrationMismatchTime,
    "no-inline-prop-on-memo-component": noInlinePropOnMemoComponent,
    "rendering-hydration-no-flicker": renderingHydrationNoFlicker,
    "rendering-script-defer-async": renderingScriptDeferAsync,
    "rendering-usetransition-loading": renderingUsetransitionLoading,

    "no-transition-all": noTransitionAll,
    "no-global-css-variable-animation": noGlobalCssVariableAnimation,
    "no-large-animated-blur": noLargeAnimatedBlur,
    "no-scale-from-zero": noScaleFromZero,
    "no-permanent-will-change": noPermanentWillChange,

    "no-eval": noEval,
    "no-secrets-in-client-code": noSecretsInClientCode,

    "no-barrel-import": noBarrelImport,
    "no-dynamic-import-path": noDynamicImportPath,
    "no-full-lodash-import": noFullLodashImport,
    "no-moment": noMoment,
    "prefer-dynamic-import": preferDynamicImport,
    "use-lazy-motion": useLazyMotion,
    "no-undeferred-third-party": noUndeferredThirdParty,

    "no-array-index-as-key": noArrayIndexAsKey,
    "no-polymorphic-children": noPolymorphicChildren,
    "rendering-conditional-render": renderingConditionalRender,
    "rendering-svg-precision": renderingSvgPrecision,
    "no-prevent-default": noPreventDefault,
    "no-uncontrolled-input": noUncontrolledInput,
    "no-document-start-view-transition": noDocumentStartViewTransition,
    "no-flush-sync": noFlushSync,

    "nextjs-no-img-element": nextjsNoImgElement,
    "nextjs-async-client-component": nextjsAsyncClientComponent,
    "nextjs-no-a-element": nextjsNoAElement,
    "nextjs-no-use-search-params-without-suspense": nextjsNoUseSearchParamsWithoutSuspense,
    "nextjs-no-client-fetch-for-server-data": nextjsNoClientFetchForServerData,
    "nextjs-missing-metadata": nextjsMissingMetadata,
    "nextjs-no-client-side-redirect": nextjsNoClientSideRedirect,
    "nextjs-no-redirect-in-try-catch": nextjsNoRedirectInTryCatch,
    "nextjs-image-missing-sizes": nextjsImageMissingSizes,
    "nextjs-no-native-script": nextjsNoNativeScript,
    "nextjs-inline-script-missing-id": nextjsInlineScriptMissingId,
    "nextjs-no-font-link": nextjsNoFontLink,
    "nextjs-no-css-link": nextjsNoCssLink,
    "nextjs-no-polyfill-script": nextjsNoPolyfillScript,
    "nextjs-no-head-import": nextjsNoHeadImport,
    "nextjs-no-side-effect-in-get-handler": nextjsNoSideEffectInGetHandler,

    "server-auth-actions": serverAuthActions,
    "server-after-nonblocking": serverAfterNonblocking,
    "server-no-mutable-module-state": serverNoMutableModuleState,
    "server-cache-with-object-literal": serverCacheWithObjectLiteral,
    "server-hoist-static-io": serverHoistStaticIo,
    "server-dedup-props": serverDedupProps,
    "server-sequential-independent-await": serverSequentialIndependentAwait,
    "server-fetch-without-revalidate": serverFetchWithoutRevalidate,

    "client-passive-event-listeners": clientPassiveEventListeners,
    "client-localstorage-no-version": clientLocalstorageNoVersion,

    "js-combine-iterations": jsCombineIterations,
    "js-tosorted-immutable": jsTosortedImmutable,
    "js-hoist-regexp": jsHoistRegexp,
    "js-hoist-intl": jsHoistIntl,
    "js-cache-property-access": jsCachePropertyAccess,
    "js-length-check-first": jsLengthCheckFirst,
    "js-min-max-loop": jsMinMaxLoop,
    "js-set-map-lookups": jsSetMapLookups,
    "js-batch-dom-css": jsBatchDomCss,
    "js-index-maps": jsIndexMaps,
    "js-cache-storage": jsCacheStorage,
    "js-early-exit": jsEarlyExit,
    "js-flatmap-filter": jsFlatmapFilter,
    "async-parallel": asyncParallel,

    "rn-no-raw-text": rnNoRawText,
    "rn-no-deprecated-modules": rnNoDeprecatedModules,
    "rn-no-legacy-expo-packages": rnNoLegacyExpoPackages,
    "rn-no-dimensions-get": rnNoDimensionsGet,
    "rn-no-inline-flatlist-renderitem": rnNoInlineFlatlistRenderitem,
    "rn-no-legacy-shadow-styles": rnNoLegacyShadowStyles,
    "rn-prefer-reanimated": rnPreferReanimated,
    "rn-no-single-element-style-array": rnNoSingleElementStyleArray,
    "rn-prefer-pressable": rnPreferPressable,
    "rn-prefer-expo-image": rnPreferExpoImage,
    "rn-no-non-native-navigator": rnNoNonNativeNavigator,
    "rn-no-scroll-state": rnNoScrollState,
    "rn-no-scrollview-mapped-list": rnNoScrollviewMappedList,
    "rn-no-inline-object-in-list-item": rnNoInlineObjectInListItem,
    "rn-animate-layout-property": rnAnimateLayoutProperty,
    "rn-prefer-content-inset-adjustment": rnPreferContentInsetAdjustment,
    "rn-pressable-shared-value-mutation": rnPressableSharedValueMutation,
    "rn-list-data-mapped": rnListDataMapped,
    "rn-list-callback-per-row": rnListCallbackPerRow,
    "rn-list-recyclable-without-types": rnListRecyclableWithoutTypes,
    "rn-animation-reaction-as-derived": rnAnimationReactionAsDerived,
    "rn-bottom-sheet-prefer-native": rnBottomSheetPreferNative,
    "rn-scrollview-dynamic-padding": rnScrollviewDynamicPadding,
    "rn-style-prefer-boxshadow": rnStylePreferBoxShadow,

    "tanstack-start-route-property-order": tanstackStartRoutePropertyOrder,
    "tanstack-start-no-direct-fetch-in-loader": tanstackStartNoDirectFetchInLoader,
    "tanstack-start-server-fn-validate-input": tanstackStartServerFnValidateInput,
    "tanstack-start-no-useeffect-fetch": tanstackStartNoUseEffectFetch,
    "tanstack-start-missing-head-content": tanstackStartMissingHeadContent,
    "tanstack-start-no-anchor-element": tanstackStartNoAnchorElement,
    "tanstack-start-server-fn-method-order": tanstackStartServerFnMethodOrder,
    "tanstack-start-no-navigate-in-render": tanstackStartNoNavigateInRender,
    "tanstack-start-no-dynamic-server-fn-import": tanstackStartNoDynamicServerFnImport,
    "tanstack-start-no-use-server-in-handler": tanstackStartNoUseServerInHandler,
    "tanstack-start-no-secrets-in-loader": tanstackStartNoSecretsInLoader,
    "tanstack-start-get-mutation": tanstackStartGetMutation,
    "tanstack-start-redirect-in-try-catch": tanstackStartRedirectInTryCatch,
    "tanstack-start-loader-parallel-fetch": tanstackStartLoaderParallelFetch,

    "query-stable-query-client": queryStableQueryClient,
    "query-no-rest-destructuring": queryNoRestDestructuring,
    "query-no-void-query-fn": queryNoVoidQueryFn,
    "query-no-query-in-effect": queryNoQueryInEffect,
    "query-mutation-missing-invalidation": queryMutationMissingInvalidation,
    "query-no-usequery-for-mutation": queryNoUseQueryForMutation,

    "no-inline-bounce-easing": noInlineBounceEasing,
    "no-z-index-9999": noZIndex9999,
    "no-inline-exhaustive-style": noInlineExhaustiveStyle,
    "no-side-tab-border": noSideTabBorder,
    "no-pure-black-background": noPureBlackBackground,
    "no-gradient-text": noGradientText,
    "no-dark-mode-glow": noDarkModeGlow,
    "no-justified-text": noJustifiedText,
    "no-tiny-text": noTinyText,
    "no-wide-letter-spacing": noWideLetterSpacing,
    "no-gray-on-colored-background": noGrayOnColoredBackground,
    "no-layout-transition-inline": noLayoutTransitionInline,
    "no-disabled-zoom": noDisabledZoom,
    "no-outline-none": noOutlineNone,
    "no-long-transition-duration": noLongTransitionDuration,

    "design-no-bold-heading": noBoldHeading,
    "design-no-redundant-padding-axes": noRedundantPaddingAxes,
    "design-no-redundant-size-axes": noRedundantSizeAxes,
    "design-no-space-on-flex-children": noSpaceOnFlexChildren,
    "design-no-three-period-ellipsis": noThreePeriodEllipsis,
    "design-no-default-tailwind-palette": noDefaultTailwindPalette,
    "design-no-vague-button-label": noVagueButtonLabel,
  },
};

export default plugin;
